config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
    resources :futurs
  resources :themes
  resources :decisions
    get 'choice/:id' => 'main#choice'
    get 'predictun/:theme/:id' => 'main#predictun'
    get 'predictdeux/:theme/:id' => 'main#predictdeux'
    get 'conclude/:theme/:id' => 'main#conclude'
    get 'submit' => 'main#submit'
    root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/decision.rb
class Decision < ApplicationRecord
    has_many :user_decisions, dependent: :destroy
    has_many :user, through: :user_decisions
    belongs_to :theme, dependent: :destroy
    belongs_to :futur
    
    validates :titre, presence: true, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 5}
    validates :second_futur, presence: true
    validates :futur_id, presence: true
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :set_decision, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

  # GET /decisions
  # GET /decisions.json
  def index
    @decisions = Decision.all.includes(:user, :futur, :theme).paginate(:page => params[:page], :per_page => 20)
      @renderer = custom_paginate_renderer
  end

  # GET /decisions/1
  # GET /decisions/1.json
  def show
  end

  # GET /decisions/new
  def new
    @decision = Decision.new
  end

  # GET /decisions/1/edit
  def edit
  end

  # POST /decisions
  # POST /decisions.json
  def create
    @decision = Decision.new(decision_params)
      
      if @decision.save
          flash[:success] = "La décision est enregistrée."
         redirect_to @decision 
      else
          flash[:error] = "La décision n'a pas été enregistrée."
          render :new
      end
  end

  # PATCH/PUT /decisions/1
  # PATCH/PUT /decisions/1.json
  def update
      
      if @decision.update(decision_params)
         flash[:success] =  "La décision a été mise à jour."
          redirect_to @decision
      else
          flash[:error] = "La décision n'a pas été mise à jour."
          render :edit
      end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    flash[:success] = "La décision a bien été supprimée."
      redirect_to decisions_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decision
      @decision = Decision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decision_params
      params.require(:decision).permit(:titre, :description, :theme_id, :first_decision, :second_futur, :futur_id)
    end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/_form.html.erb
<%= simple_form_for @decision do |f| %>

  <div class="form-group">
    <%= f.input :titre, label: 'Titre de la décision' %>
  </div>

  <div class="form-group">
    <%= f.input :description, label: 'Description de la décision', input_html: {cols: '50', rows: '10'} %>
  </div>

  <div class="form-group">
    <%= f.association :theme, label_method: :nom, label: 'Thème', as: :select %>
  </div>
  
  <div class="form-group">
      <%= f.association :futur, label_method: :titre, label: 'Futur lié', as: :select, input_html: {multiple: false, required: true} %>
  </div>
  
  <div class="form-group">
     <label for="decision_second_futur">Futur suivant</label>
      <%= select :decision, :second_futur, Futur.all.collect {|futur| [futur.titre, futur.titre]}%>
  </div>
  
  <div class="form-group">
      <%= f.input :first_decision, label: 'Première décision' %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Modifier la décision</h1>

<%= render 'form', decision: @decision %> <br><br>

<%= link_to 'Montrer', @decision, class: 'btn btn-success' %> |
<%= link_to 'Retour', decisions_path, class: 'btn' %>

app/views/decisions/index.html.erb
<h1>Décisions</h1>


<%= will_paginate @decisions, renderer: @renderer %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
        <th>Thème</th>
        <th>Futur lié</th>
        <th>Futur suivant</th>
        <th>Première décision</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @decisions.each do |decision| %>
      <tr>
        <td><%= decision.titre %></td>
        <td><%= texteCourt(decision.description) %></td>
        <td><%= link_to decision.theme.nom.to_s, decision.theme, class: 'btn' %></td>
        <td><%= link_to texteCourt(decision.futur.titre), decision.futur, class: 'btn' %></td>
        <td>
        <% if decision.second_futur.length > 0 %>
        <%= texteCourt(decision.second_futur) %>
        <% else %>
        Pas de futur suivant
        <% end %>
        </td>
        <td><%= booleanToText(decision.first_decision) %></td>
        <td>
        <% if can? :show, @decision %>
        <%= link_to 'Afficher', decision, class: 'btn btn-primary' %>
        <% end %>
        </td>
        <td>
        <% if can? :update, @decision %>
        <%= link_to 'Modifier', edit_decision_path(decision), class: 'btn' %>
        <% end %>
        </td>
        <td>
        <% if can? :destroy, @decision %>
        <%= link_to 'Supprimer', decision, class: 'btn btn-error', method: :delete, data: { confirm: 'Êtes-vous sûr(e) de supprimer cette décision ?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, @decision %>
<%= link_to 'Créer une décision', new_decision_path, class: 'btn btn-success' %>
<% end %>


<%= link_to 'Retour au jeu', root_url, class: 'btn' %>

app/views/decisions/new.html.erb
<h1>Créer une décision</h1>

<%= render 'form', decision: @decision %> <br><br>

<%= link_to 'Retour', decisions_path, class: 'btn' %>

app/views/decisions/show.html.erb
<p>
  <strong>Titre:</strong>
  <%= @decision.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @decision.description %>
</p>

<p>
  <strong>Thème:</strong>
  <%= @decision.theme.nom %>
</p>

<p>
    <strong>Futur lié:</strong>
    <%= @decision.futur.titre %>
</p>

<p>
    <strong>Description du futur:</strong>
    <%= @decision.futur.description %>
</p>

<p>
    <strong>Second futur:</strong>
    <% if @decision.second_futur.length > 0 %>
    <%= @decision.second_futur %>
    <% else %>
    Pas de futur suivant
    <% end %>
</p>

<p>
    <strong>Première décision:</strong>
    <%= booleanToText(@decision.first_decision) %>
</p>

<%= link_to 'Modifier', edit_decision_path(@decision), class: 'btn' %> |
<%= link_to 'Retour', decisions_path, class: 'btn' %>