config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
    resources :futurs
  resources :themes
  resources :decisions
    get 'choice/:id' => 'main#choice'
    get 'predictun/:theme/:id' => 'main#predictun'
    get 'predictdeux/:theme/:id' => 'main#predictdeux'
    get 'conclude/:theme/:id' => 'main#conclude'
    get 'submit' => 'main#submit'
    root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
class Theme < ApplicationRecord
    
    belongs_to :futur, dependent: :destroy
    
    validates :nom, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 5}
    validates :futur_id, presence: true
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all.paginate(:page => params[:page], :per_page => 20)
      @renderer = custom_paginate_renderer
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)
      
      if @theme.save
          flash[:success] = "Le thème a bien été crée."
         redirect_to @theme 
      else
          flash[:error] = "Le thème n'a pas été crée, le nom du thème est requis, ainsi que la description et le futur de départ"
          render :new
      end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
      
      if @theme.update(theme_params)
         flash[:success] = "Le thème a été mis à jour"
          redirect_to @theme
      else
          flash[:error] = "Le thème n'a pas pu être mis à jour, le nom du thème est requis, ainsi que la descripion et le futur de départ"
          render :edit
      end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    flash[:warning] = "Le thème a été supprimé"
      redirect_to themes_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:nom, :description, :futur_id)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= simple_form_for @theme do |f| %>

  <div class="form-group">
    <%= f.input :nom, label: 'Nom' %>
  </div>

  <div class="form-group">
    <%= f.input :description, label: 'Description', input_html: {cols: '50', rows: '10'} %>
  </div>
  
  <div>
      <%= f.association :futur, label_method: :titre, label: 'Futur de départ', as: :select %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Modifier le thème</h1>

<%= render 'form', theme: @theme %> <br><br>

<%= link_to 'Afficher', @theme, class: 'btn' %> |
<%= link_to 'Retour', themes_path, class: 'btn' %>

app/views/themes/index.html.erb
<h1>Thèmes</h1>

<%= will_paginate @futurs, renderer: @renderer %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Premier futur</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.nom %></td>
        <td><%= texteCourt(theme.description) %></td>
        <td><%= texteCourt(theme.futur.titre) %></td>
        <td>
        <% if can? :read, @theme %>
        <%= link_to 'Afficher', theme, class: 'btn btn-primary' %>
        <% end %>
        </td>
        <td>
        <% if can? :update, @theme %>
        <%= link_to 'Modifier', edit_theme_path(theme), class: 'btn' %>
        <% end %>
        </td>
        <td>
        <% if can? :destroy, @theme %>
        <%= link_to 'Supprimer', theme, class: 'btn btn-error', method: :delete, data: { confirm: 'Êtes-vous sûr(e) de supprimer ce thème ?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, @theme %>
<%= link_to 'Créer un thème', new_theme_path, class: 'btn btn-success' %>
<% end %>


<%= link_to 'Retour au jeu', root_path, class: 'btn' %>

app/views/themes/new.html.erb
<h1>Créer un thème</h1>

<%= render 'form', theme: @theme %> <br><br>

<%= link_to 'Retour', themes_path, class: 'btn' %>

app/views/themes/show.html.erb
<p>
  <strong>Nom:</strong>
  <%= @theme.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @theme.description %>
</p>

<p>
    <strong>Futur de départ:</strong>
    <%= @theme.futur.titre %>
</p>

<p>
    <strong>Description du futur de départ:</strong>
    <%= @theme.futur.description %>
</p>

<%= link_to 'Modifier', edit_theme_path(@theme), class: 'btn' %> |
<%= link_to 'Retour', themes_path, class: 'btn' %>