config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
    resources :futurs
  resources :themes
  resources :decisions
    get 'choice/:id' => 'main#choice'
    get 'predictun/:theme/:id' => 'main#predictun'
    get 'predictdeux/:theme/:id' => 'main#predictdeux'
    get 'conclude/:theme/:id' => 'main#conclude'
    get 'submit' => 'main#submit'
    root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/futur.rb
class Futur < ApplicationRecord
   
    has_many :decision
    
    validates :titre, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 5}
    validates :description, presence: true, length: {minimum: 5}
end

app/controllers/futurs_controller.rb
class FutursController < ApplicationController
  before_action :set_futur, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

  # GET /futurs
  # GET /futurs.json
  def index
    @futurs = Futur.all.includes(:decision).paginate(:page => params[:page], :per_page => 15)
      @renderer = custom_paginate_renderer
  end

  # GET /futurs/1
  # GET /futurs/1.json
  def show
  end

  # GET /futurs/new
  def new
    @futur = Futur.new
  end

  # GET /futurs/1/edit
  def edit
  end

  # POST /futurs
  # POST /futurs.json
  def create
    @futur = Futur.new(futur_params)
      @futur.titre = @futur.titre.gsub(/"/, '\'')
      
      if @futur.save
         flash[:success] = "Le futur a été sauvegardé."
          redirect_to @futur 
      else
          flash[:error] = "Le futur n'a pas pu être sauvegardé."
          render :new
      end
  end

  # PATCH/PUT /futurs/1
  # PATCH/PUT /futurs/1.json
  def update
      
      if @futur.update(futur_params)
          flash[:success] = "Le futur a été modifié"
         redirect_to @futur 
      else
          flash[:error] = "Le futur n'a pas pu être modifié"
          render :edit
      end
  end

  # DELETE /futurs/1
  # DELETE /futurs/1.json
  def destroy
    @futur.destroy
      flash[:warning] = "Le futur a été supprimé."
      redirect_to futurs_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_futur
      @futur = Futur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def futur_params
      params.require(:futur).permit(:titre, :description)
    end
end

app/helpers/futurs_helper.rb
module FutursHelper
end

app/views/futurs/_form.html.erb
<%= simple_form_for @futur do |f| %>

  <div class="form-group">
    <%= f.input :titre, label: 'Titre' %>
  </div>

  <div class="form-group">
    <%= f.input :description, label: 'Description', input_html: {cols: '50', rows: '10'} %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/futurs/edit.html.erb
<h1>Modifier le futur</h1>

<%= render 'form', futur: @futur %> <br><br>

<%= link_to 'Modifier', @futur, class: 'btn' %> |
<%= link_to 'Retour', futurs_path, class: 'btn' %>

app/views/futurs/index.html.erb
<h1>Futurs</h1>

<%= will_paginate @futurs, renderer: @renderer %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @futurs.each do |futur| %>
      <tr>
        <td><%= futur.titre %></td>
        <td><%= texteCourt(futur.description) %></td>
        <td>
        <% if can? :show, @futur %>
        <%= link_to 'Afficher', futur, class: 'btn btn-primary' %>
        <% end %>
        </td>
        <td>
        <% if can? :update, @futur %>
        <%= link_to 'Modifier', edit_futur_path(futur), class: 'btn' %>
        <% end %>
        </td>
        <td>
        <% if can? :destroy, @futur %>
        <%= link_to 'Supprimer', futur, class: 'btn btn-error', method: :delete, data: { confirm: 'Êtes-vous sûr(e) de supprimer ce futur ?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, @futur %>
<%= link_to 'Créer un futur', new_futur_path, class: 'btn btn-success' %>
<% end %>


<%= link_to 'Retour au jeu', root_url, class: 'btn' %>

app/views/futurs/new.html.erb
<h1>Créer un futur</h1>

<%= render 'form', futur: @futur %> <br><br>

<%= link_to 'Retour', futurs_path, class: 'btn' %>

app/views/futurs/show.html.erb
<p>
  <strong>Titre:</strong>
  <%= @futur.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @futur.description %>
</p>


<%= link_to 'Modifier', edit_futur_path(@futur), class: 'btn' %> |
<%= link_to 'Retour', futurs_path, class: 'btn' %> |
<%= link_to 'Retour aux décisions', decisions_path, class: 'btn' %>