config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
    resources :futurs
  resources :themes
  resources :decisions
    get 'choice/:id' => 'main#choice'
    get 'predictun/:theme/:id' => 'main#predictun'
    get 'predictdeux/:theme/:id' => 'main#predictdeux'
    get 'conclude/:theme/:id' => 'main#conclude'
    get 'submit' => 'main#submit'
    root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meet The Future</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
   <section>
       <% if user_signed_in? %>
       
       <% if current_user.has_role? :admin %>
       
       <%= link_to 'Décisions', decisions_url, class: 'btn btn-primary btn-lg' %>
   <%= link_to 'Futurs', futurs_url, class: 'btn btn-primary btn-lg' %>
   <%= link_to 'Thèmes', themes_url, class: 'btn btn-primary btn-lg' %> <br><br>
      
      <% end %>
       
        <%= link_to current_user.pseudo, edit_user_registration_url, class: 'btn' %> - <%= link_to 'Se déconnecter', destroy_user_session_path, data: {confirm: "Voulez-vous vous déconnecter ?"}, method: :delete, class: 'btn btn-error' %>
        <% $user = current_user %>
       <% else %>
       <%= link_to 'Se connecter', new_user_session_url, class: 'btn' %> - <%= link_to "S'inscrire", new_user_registration_url, class: 'btn' %>
       <% end %>
   </section><br>
   
   <% flash.each do |name, msg| %>
   <div class="toast toast-<%= name %>">
       <p><%= msg %></p>
   </div>
   <% end %> <br>
   
    <%= yield %>
  </body>
</html>